---
title: "Homework 7"
subtitle: "BSTA 550"
description: "Due: Thursday November 30, 2023 at 11pm"
date-modified: "11/06/2023"
date: "11/30/2023"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

::: callout-caution
## Split up this homework over the 2 weeks!

This homework is extra long! While I don't want you to worry about turning something in over your break, I do not recommend saving it all for after the break. I recommend having Chapter 25-27 problems completed when you get back from your break.
:::

## Directions

[Please turn in this homework on Sakai.](https://sakai.ohsu.edu/portal/site/BSTA-550-1-12619-F23/tool/085b18e7-8118-4a51-ace5-0255aa46136e) Please submit your homework in pdf format. You can type your work on your computer or submit a photo of your written work or any other method that can be turned into a pdf. Please let me know if you greatly prefer to submit a physical copy. We can work out another way for you to turn in homework.

**Try to complete all of the problems listed below at some point this quarter! You may want to save some of them for studying later!** Only turn in the ones listed in the "Turn In" column. Please submit problems in the order they are listed.

The more work you include that shows your thought process, the more I can give you feedback.

::: center
+---------+---------------------------+----------------------------------+
| Chapter | Turn In                   | Extra Problems                   |
+:=======:+:=========================:+:================================:+
| 25      | TB \# 18, NTB \# 1        | \# 1, 4, 8, 17, 23, 24           |
|         |                           |                                  |
|         |                           | Slide examples: 2, 3.3, 4        |
+---------+---------------------------+----------------------------------+
| 26\*    | TB \# 12\*\*, NTB \# 2, 3 | \# 7, 9, 19, 20                  |
|         |                           |                                  |
|         |                           | Slide examples: 3                |
+---------+---------------------------+----------------------------------+
| 27      | TB \# 12\*\*\*            | \# 6, 8, 13, 17                  |
|         |                           |                                  |
|         |                           | Slide examples: 1.2              |
+---------+---------------------------+----------------------------------+
| 28      | TB \# 18                  | TB \# 1, 10                      |
+---------+---------------------------+----------------------------------+
| 29[^1]  | NTB \# 4-6                | TB \# 10, 14, 23, 26, 11, 13, 32 |
+---------+---------------------------+----------------------------------+
| 30      |                           | TB \# 4, 7-12                    |
+---------+---------------------------+----------------------------------+
:::

[^1]: I recommend doing the Chapter 29 Extra Problems in the order listed.

\* Although within Chapter 26, these exercises are primarily practicing the material from Chapter 25.

\*\* For this problem, you only need to set up the integrals!!

\*\*\* For Ch 27 \# 12, in order to find the conditional densities in parts (a) and (b), you will need to calculate $f_Y(y)$ for the specific regions of $y$ specified. After finding the conditional densities in parts (a) and (b), also calculate the conditional probabilities below. Please submit these together with your other work in parts (a) and (b): Find $\mathbb{P}[0.5 < X < 3 | Y = 4]$. Find $\mathbb{P}[0.5 < X < 3 | Y = 7]$.

## Non-textbook problems (NTB)

1.  Let $X_1, X_2, \ldots, X_n$ be i.i.d. random variables with common pdf $f_X(x)$ and cdf $F_X(x)$. Find the pdf for the random variable $Z$, where $Z = max(X_1, X_2, \ldots, X_n)$.

2.  Let $X$ and $Y$ be independent random variables with respective pdf's $f_X(x)=\frac{1}{5}$, for $0\leq x\leq 5$, and $f_Y(y)=2e^{-2y}$, for $y>0$.

    a.  Find the joint distribution $f_{X,Y}(x,y)$.
    b.  Find the probability that $X$ is less than $Y$.
    c.  Let $Z$ be the random variable that is the smaller of $X$ and $Y$. Find the cumulative distribution function for $Z$.
    d.  Find the pdf for Z.

3.  Suppose that the random variables $X$ and $Y$ have joint density $f_{X,Y}(x,y)$, for $0<x<1$, and $\frac{1}{2}<y<1$. Set up the equation for the cdf of $Z$, where $Z=X/Y$.

    *Hint: First determine what the possible values for* $Z$ are. Then make a sketch of the domain of the joint pdf and shade in the region representing the cdf of Z for different values of $z$. Make sure to pay close attention to how the region we need to integrate over changes as $z$ changes. The cdf has two different cases depending on the value of $z$. Plug in specific values of $z$ and shade in the region representing the cdf to see why two different cases are needed.

4.  Let $f_X(x)=\lambda e^{-\lambda x}$ for $x>0$, where $\lambda>0$.

    a.  Show $Var[X]=\frac{1}{\lambda^2}$. You may use the result from class for $\mathbb{E}[X]$ without first proving it.

5.  A shipping company handles containers in three different sizes: (1) 27 $ft^3$ (3 x 3 x 3), (2) 125 $ft^3$, and (3) 512 $ft^3$. Let $X_i$ ($i = 1, 2, 3$) denote the number of type $i$ containers shipped during a given week. Suppose that $\mu_1 =200,\sigma_1=10,\mu_2 =250,\sigma_2=12,\mu_3 =100,\sigma_3=8$.

    a.  Assuming that $X_1,X_2,X_3$ are independent, calculate the expected value and variance of the total volume shipped.

    b.  Would your calculations necessarily be correct if the $X_i$'s were not independent? Explain.

6.  Suppose your waiting time for a bus in the morning is uniformly distributed on \[0, 8\] (minutes), whereas waiting time in the evening is uniformly distributed on \[0, 10\] (minutes) independent of morning waiting time. *Make sure to FIRST set up an equation for calculating the total waiting time in each question before calculating the mean and variance of the total waiting time.* *You may use results from class for the expected value and variance of uniform r.v.'s without proving them.*

    a.  If you take the bus each morning and evening for a week (7 days), what is your total expected waiting time?

    b.  What is the variance of your total waiting time?

    c.  What are the expected value and variance of the difference between morning and evening waiting times on a given day?

    d.  What are the expected value and variance of the difference between total morning waiting time and total evening waiting time for a particular week?

## Some select answers

Selected answers (or hints) not provided at the end the book:

-   Chapter 25

    -   \# 4:   7/16

    -   \# 8:  (a) $\frac{25}{228}$     (b) $f_X(x)=\frac{1}{12}(x+1)$, for $0\leq x\leq 4$     (c) $f_Y(y)=\frac{3}{76}(y^2+1)$, for $0\leq y\leq 4$

    -   \# 18:  5/6

    -   \# 24:  (a) $f_X(x)=-2e^{-2x}+2e^{-x}$, for $x\geq 0$     (b) $f_Y(y)=2e^{-2y}$, for $y\geq 0$

-   Chapter 26

    -   \# 12:  (b) $\frac{233}{256}$     (c) $\frac{65}{256}$     (d) $\frac{1}{512}$

    -   \# 20:  (a) Yes.     (b) $\frac{15}{16}$

    -   NTB \# 3: (b) 0.09999546   (d) $f_Z(z) =\Big(\frac{11}{5} - \frac{2z}{5}\Big)e^{-2z}$, for what values of $z$?

-   Chapter 27

    -   \# 6: $f_{X|Y}(x|y)=\frac{e^{-x/4-y/5}}{4(e^{-y/5}-e^{-9y/20})}$, for $0< x< y$

    -   \# 8: $f_{X|Y}(x|y)=\frac{1-x^2}{1-y-\frac{(1-y)^3}{3}}$, for $0\leq x, 0\leq y, x+y\leq 1$

    -   \# 12: (a) $f_{X|Y}(x|y)=\frac{1}{2}$    (c) $\frac{4}{7}$

-   Chapter 28

    -   \# 10: (a) 8/9     (b) 14/3     

    -   \# 18: 4/5

-   Chapter 29

    -   \# 10: (a) 26/81     (b) 74/9

    -   \# 14: (a) 67/3     (b) 1/14     (c) 25/12     (d) $\sqrt{25/12}$

    -   \# 26: 250

    -   \# 32: See notes (or book) for the proof from the discrete random variables case. The proof doesn't depend on what type of random variable (discrete vs. continuous) is being used.

    -   NTB \# 6: (a) 63     (b) 287/3     (c) -1, 41/3     (d) -7, 287/3

-   Chapter 30

    -   \# 4: $f_x(x)=1/2$ for $2\leq x\leq 4$

    -   \# 8: (a) T     (b) T     (c) F

    -   \# 10: (a) F     (b) T

    -   \# 12: (a) T     (b) T     (c) F     (d) T
