---
title: "Chapter 14 - 18"
author: "Meike Niederhausen and Nicky Wakim"
date: "10/25/2023"
categories: ["Week 5"]
title-slide-attributes:
    data-background-color: "#006a4e"
format: 
  revealjs:
    theme: [default, simple_NW.scss]
    toc: true
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1955
    height: 1100
    footer: Chapter 14-18 Slides
---

## Learning Objectives

# Chapter 14: Bernoulli RVs

## Bernoulli RV

**Scenario:** One trial, with outcome success or failure.

**Properties of Bernoulli r.v.'s**

## Example 1

::: example
**Example 1**. * *

-   *We roll a fair 6-sided die.*

-   *We get \$1 if we roll a 5, and nothing otherwise.*

-   *Let $X$ be how much money we get.*

-   *Find the mean and variance of $X$.*
:::

**Solution:**

## Example 2

::: example
**Example 2**. * *

-   *Suppose we roll a fair 6-sided die 50 times.*

-   *We get \$1 every time we roll a 5, and nothing otherwise.*

-   *Let $X$ be how much money we get on the 50 rolls.*

-   *Find the mean and variance of $X$.*
:::

**Solution:**

# Chapter 15: Binomial RVs {#chapter-15-binomial-r.v.s .unnumbered}

## meh

**Scenario:** There are $n$ independent trials, each resulting in a
success or failure, with constant probability in each trial. We are
counting the number of successes (or failures).


## Properties of Binomial RVs
