---
title: "Calculus Review"
author: "Meike Niederhausen and Nicky Wakim"
date: "11/06/2023"
title-slide-attributes:
    data-background-color: "#006a4e"
categories: ["Week 7"]
format: 
  revealjs:
    theme: [default, simple_NW.scss]
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1955
    height: 1100
    footer: Chapter 24 Slides
---

## Learning Objectives

1. Find derivatives of continuous functions with one variable

2. Find antiderivatives and integrals of functions with one variable

# Differentiation

## Find the *derivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 1.1
:::
::: ex-cont
$f(x) = 2$
:::
:::

::: theorem
::: thm-title
Derivative of a constant
:::
::: thm-cont
$$\dfrac{d}{dx} c = 0$$
:::
:::

:::

:::

## Find the *derivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 1.2
:::
::: ex-cont
$f(x) = 2x$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 1.3
:::
::: ex-cont
$f(x) = 2x+2$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 1.4
:::
::: ex-cont
$f(x) = x^2$
:::
:::

::: theorem
::: thm-title
Derivative of $x$ to a constant
:::
::: thm-cont
$$\dfrac{d}{dx} x^n = nx^{n-1}$$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 1.5
:::
::: ex-cont
$f(x) = 3\sqrt{x}+\frac2x+5$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 1.6
:::
::: ex-cont
$f(x) = e^x$
:::
:::

::: theorem
::: thm-title
Derivative of exponential function
:::
::: thm-cont
$\dfrac{d}{dx} e^x = e^x$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 1.7
:::
::: ex-cont
$f(x) = \ln(x)$
:::
:::

::: theorem
::: thm-title
Derivative of logarithm
:::
::: thm-cont
$\dfrac{d}{dx} ln(x) = \dfrac{1}{x}$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="38%"}
::: example
::: ex-title
Example 1.8
:::
::: ex-cont
$f(x) = x^2 e^x$
:::
:::

::: theorem
::: thm-title
Product Rule
:::
::: thm-cont
$\dfrac{d}{dx} f(x)g(x) = f'(x)g(x) + f(x)g'(x)$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="35%"}
::: example
::: ex-title
Example 1.9
:::
::: ex-cont
$f(x) = \frac{x^5}{2x+7}$
:::
:::

::: theorem
::: thm-title
Quotient Rule
:::
::: thm-cont
$\dfrac{d}{dx} \dfrac{f(x)}{g(x)} = \dfrac{g(x)f'(x) - f(x)g'(x)}{\big(g(x)\big)^2}$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="33%"}
::: example
::: ex-title
Example 1.10
:::
::: ex-cont
$f(x) = e^{-2x+7}$
:::
:::

::: theorem
::: thm-title
Chain Rule
:::
::: thm-cont
$\dfrac{d}{dx} f\big(g(x)\big)= f'\big(g(x)\big)g'(x)$
:::
:::

:::
:::

## Find the *derivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 1.11
:::
::: ex-cont
$f(x) = \ln(x^2)$
:::
:::

:::
:::


# Integration

## Find the *antiderivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 2.1
:::
::: ex-cont
$f(x) = 2$
:::
:::

:::
:::

## Find the *antiderivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 2.2
:::
::: ex-cont
$f(x) = x$
:::
:::

::: theorem
::: thm-title
Integration of x to a constant
:::
::: thm-cont
$\displaystyle\int x^n dx = \dfrac{x^{n+1}}{n+1} + c$
:::
:::

:::
:::

## Find the *antiderivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 2.3
:::
::: ex-cont
$f(x) = \frac1x$
:::
:::

:::
:::

## Find the *antiderivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 2.4
:::
::: ex-cont
$f(x) = x^{3/2}$
:::
:::

:::
:::

## Find the *antiderivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 2.5
:::
::: ex-cont
$f(x) = e^x$
:::
:::

:::
:::

## Find the *antiderivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 2.6
:::
::: ex-cont
$f(x) = e^{-x}$
:::
:::

:::
:::

## Find the *antiderivative* of the following function

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 2.7
:::
::: ex-cont
$f(x) = e^{-2x}$
:::
:::

:::
:::

## Solve the following integral

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 3.1
:::
::: ex-cont
$\displaystyle\int_0^1 (2x+x^5)dx$
:::
:::

:::
:::

## Solve the following integral

::: columns
::: {.column width="35%"}
::: example
::: ex-title
Example 3.2
:::
::: ex-cont
$\displaystyle\int_2^3 e^{-x}dx$
:::
:::

::: theorem
::: thm-title
U-substitution
:::
::: thm-cont
$\displaystyle\int f\big(g(x)\big) g'(x) dx = \displaystyle\int f(u) dx$
:::
:::

:::
:::

## Solve the following integral

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 3.3
:::
::: ex-cont
$\displaystyle\int_2^3 x e^{x^2}dx$
:::
:::

:::
:::

## Solve the following integral

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 3.4
:::
::: ex-cont
$\displaystyle\int_0^{\infty} x e^{-x}dx$
:::
:::

::: theorem
::: thm-title
Integrating by Parts
:::
::: thm-cont
$\displaystyle\int f(x) g'(x) dx = f(x)g(x) - \\ \displaystyle\int f'(x) g(x) dx$

OR

$\displaystyle\int_a^b u dv = uv\bigg|^b_a - \displaystyle\int_a^b vdu$
:::
:::

:::
:::

## Solve the following integral

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 3.5
:::
::: ex-cont
$\displaystyle\int_1^2 x^2 \ln(x)dx$
:::
:::

:::
:::

## Solve the following integral

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 3.6
:::
::: ex-cont
$\displaystyle\int_1^2 \ln(x)dx$
:::
:::

:::
:::

## Solve the following integral

::: columns
::: {.column width="30%"}
::: example
::: ex-title
Example 3.7
:::
::: ex-cont
$\displaystyle\int_1^2 x^2 e^{x}dx$
:::
:::

:::
:::

